name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker
    steps:
      - name: Trigger deployment webhook
        run: |
          curl --fail-with-body \
            --silent \
            --show-error \
            --request POST \
            --data-urlencode "direct=true" \
            "${{ secrets.PLOI_DEPLOY_URL }}"
